development:
  address: "smtp.mailgun.org"
  port: 587
  domain: "TonightLetsDrinkDrink"
  authentication: "plain"
  user_name: ENV["mailgun_username"]
  password: ENV["mailgun_password"]
  enable_starttls_auto: true 

production:
  address: "smtp.mailgun.org"
  port: 587
  domain: "TonightLetsDrinkDrink"
  authentication: "plain"
  user_name: ENV["mailgun_username"]
  password: ENV["mailgun_password"]
  enable_starttls_auto: true 