drink = Drink.create([
  { name: 'Beer', display_name: '啤酒' ,volume_alcohol: '4.5', img_path: 'https://thumbs2.imgbox.com/d7/6e/LNhbdZzZ_t.jpeg' },
  { name: 'Cider', display_name: '蘋果酒' ,volume_alcohol: '4.5', img_path: 'https://thumbs2.imgbox.com/f8/f5/Ivm5xGkh_t.jpeg' },
  { name: 'Craft-Beer', display_name: '精釀啤酒' ,volume_alcohol: '6', img_path: 'https://thumbs2.imgbox.com/a2/f3/sBXaxZXS_t.jpeg' },
  { name: 'Red-Wine', display_name: '紅葡萄酒' ,volume_alcohol: '12.5', img_path: 'https://thumbs2.imgbox.com/66/56/rXdHAFbB_t.jpeg' },
  { name: 'White-Wine', display_name: '白葡萄酒' ,volume_alcohol: '12.5', img_path: 'https://thumbs2.imgbox.com/dc/1a/hMOv7U9v_t.jpeg' },
  { name: 'Champagne', display_name: '香檳' ,volume_alcohol: '12.5', img_path: 'https://thumbs2.imgbox.com/fe/12/AHIKf4dz_t.jpeg' },
  { name: 'Tequila', display_name: '龍舌蘭' ,volume_alcohol: '40', img_path: 'https://thumbs2.imgbox.com/f7/f4/a5h9T0iq_t.jpeg' },
  { name: 'Vodka', display_name: '伏特加' ,volume_alcohol: '40', img_path: 'https://thumbs2.imgbox.com/34/71/hgmYwfnE_t.jpeg' },
  { name: 'Whisky', display_name: '威士忌' ,volume_alcohol: '40', img_path: 'https://thumbs2.imgbox.com/79/c5/A3ePrI7a_t.jpeg' },
  { name: 'Umeshu', display_name: '梅酒' ,volume_alcohol: '15', img_path: 'https://thumbs2.imgbox.com/bc/43/BhUOfwu9_t.jpg' },
  { name: 'Sake', display_name: '清酒' ,volume_alcohol: '13', img_path: 'https://thumbs2.imgbox.com/bb/66/4KSFBxS5_t.jpg' },
  { name: 'Soju', display_name: '燒酒' ,volume_alcohol: '20.1', img_path: 'https://thumbs2.imgbox.com/db/b5/4a0jO6hd_t.jpeg' },
  { name: 'Gao-Liang-38', display_name: '38°高粱' ,volume_alcohol: '38', img_path: 'https://thumbs2.imgbox.com/f4/32/T1tBQWT9_t.jpg' },
  { name: 'Gao-Liang-58', display_name: '58°高粱' ,volume_alcohol: '58', img_path: 'https://thumbs2.imgbox.com/c6/0b/6aVkV1Vh_t.png' },
])